##############################################################################
# Orchestration – Ingestion Microservice
# Engine  : PySpark 3.x
# Type    : Batch job (no restart policy)
# Network : uni_net (external bridge)
##############################################################################

# ── Scheduling ─────────────────────────────────────────────────────────────
# Not restarted automatically — triggered by the scheduler only via
# `docker compose run --rm ingestion`.

services:

  ingestion:
    build:
      context: ../../microservices/ingestion
      dockerfile: docker/Dockerfile
    image: uni/ingestion:1.0.0            # versioned image (Maintainability)
    container_name: ingestion
    user: "1000:1000"                     # non-root container (Security)
    # No restart policy — batch job, not a long-running service.
    environment:
      - HDFS_URL=hdfs://namenode:9000
      - MODE=${MODE:-daily}               # "initial" (Script A) | "daily" (Script B / cron)
      - EVENT_DATE=${EVENT_DATE:-}        # YYYY-MM-DD UTC, set by daily pipeline script
    volumes:
      - ../../microservices/ingestion:/app/microservices/ingestion
      - ../../data/EdNet-KT4:/app/EdNet-KT4
      - ../../data/EdNet-Contents:/app/EdNet-Contents
    depends_on:
      namenode:
        condition: service_healthy
    networks:
      - uni_net

# ── Network (external) ────────────────────────────────────────────────────
networks:
  uni_net:
    external: true
